//! File management for Azure AI Foundry Agent Service.
//!
//! Files can be uploaded to the service for use with agents (e.g., for file search
//! or code interpreter). This module provides functions to upload, retrieve, list,
//! delete, and download files.
//!
//! ## Example
//!
//! ```rust,no_run
//! use azure_ai_foundry_core::client::FoundryClient;
//! use azure_ai_foundry_core::auth::FoundryCredential;
//! use azure_ai_foundry_agents::file::{self, FilePurpose};
//!
//! # async fn example() -> Result<(), Box<dyn std::error::Error>> {
//! let client = FoundryClient::builder()
//!     .endpoint("https://your-resource.services.ai.azure.com")
//!     .credential(FoundryCredential::api_key("your-key"))
//!     .build()?;
//!
//! // Upload a file
//! let file = file::upload(
//!     &client,
//!     "data.jsonl",
//!     b"line1\nline2\n".to_vec(),
//!     FilePurpose::Assistants,
//! ).await?;
//! println!("Uploaded file: {}", file.id);
//!
//! // Download file content
//! let content = file::download(&client, &file.id).await?;
//! println!("Downloaded {} bytes", content.len());
//!
//! // Delete the file
//! file::delete(&client, &file.id).await?;
//! # Ok(())
//! # }
//! ```

use azure_ai_foundry_core::client::FoundryClient;
use azure_ai_foundry_core::error::{FoundryError, FoundryResult};
use serde::{Deserialize, Serialize};

use crate::models::API_VERSION;

/// Maximum file size accepted by Azure AI Foundry (512 MB).
pub const MAX_FILE_SIZE_BYTES: usize = 512 * 1024 * 1024;

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/// The purpose of an uploaded file.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum FilePurpose {
    /// File used by agents (e.g., for file search or code interpreter).
    Assistants,
    /// Output file generated by an agent.
    AssistantsOutput,
    /// File used for fine-tuning.
    #[serde(rename = "fine-tune")]
    FineTune,
}

impl FilePurpose {
    /// Return the string representation used by the API.
    ///
    /// This matches the serialized form used in multipart form fields.
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Assistants => "assistants",
            Self::AssistantsOutput => "assistants_output",
            Self::FineTune => "fine-tune",
        }
    }
}

/// A file object stored in the service.
#[derive(Debug, Clone, Deserialize)]
pub struct FileObject {
    /// Unique identifier for the file.
    pub id: String,

    /// Object type, always "file".
    pub object: String,

    /// File size in bytes.
    pub bytes: u64,

    /// Unix timestamp when the file was created.
    pub created_at: u64,

    /// Original filename.
    pub filename: String,

    /// The intended purpose of the file.
    pub purpose: FilePurpose,

    /// Processing status of the file.
    pub status: Option<String>,

    /// Details about the processing status.
    pub status_details: Option<String>,
}

/// Response from listing files.
#[derive(Debug, Clone, Deserialize)]
pub struct FileList {
    /// Object type, always "list".
    pub object: String,

    /// List of files.
    pub data: Vec<FileObject>,

    /// Whether there are more files to fetch.
    pub has_more: bool,
}

/// Response from deleting a file.
#[derive(Debug, Clone, Deserialize)]
pub struct FileDeletionResponse {
    /// ID of the deleted file.
    pub id: String,

    /// Object type, always "file.deleted".
    pub object: String,

    /// Whether the deletion was successful.
    pub deleted: bool,
}

// ---------------------------------------------------------------------------
// API functions
// ---------------------------------------------------------------------------

/// Upload a file to the service.
///
/// # Arguments
///
/// * `client` - The Foundry client.
/// * `filename` - The name of the file.
/// * `data` - The file content as bytes.
/// * `purpose` - The intended purpose of the file.
///
/// # Errors
///
/// Returns an error if:
/// - The filename is empty or whitespace
/// - The data is empty
/// - The data exceeds [`MAX_FILE_SIZE_BYTES`] (512 MB)
///
/// # Example
///
/// ```rust,no_run
/// # use azure_ai_foundry_core::client::FoundryClient;
/// # use azure_ai_foundry_agents::file::{self, FilePurpose};
/// # async fn example(client: &FoundryClient) -> azure_ai_foundry_core::error::FoundryResult<()> {
/// let file = file::upload(client, "data.jsonl", b"content".to_vec(), FilePurpose::Assistants).await?;
/// println!("Uploaded: {}", file.id);
/// # Ok(())
/// # }
/// ```
///
/// # Tracing
///
/// Emits a span named `foundry::files::upload` with fields `filename` and `purpose`.
#[tracing::instrument(
    name = "foundry::files::upload",
    skip(client, data),
    fields(filename = %filename, purpose = ?purpose)
)]
pub async fn upload(
    client: &FoundryClient,
    filename: &str,
    data: impl Into<bytes::Bytes>,
    purpose: FilePurpose,
) -> FoundryResult<FileObject> {
    let data: bytes::Bytes = data.into();

    if filename.trim().is_empty() {
        return Err(FoundryError::validation_field(
            "filename",
            "filename cannot be empty",
        ));
    }
    if data.is_empty() {
        return Err(FoundryError::validation_field(
            "data",
            "file data cannot be empty",
        ));
    }
    if data.len() > MAX_FILE_SIZE_BYTES {
        return Err(FoundryError::validation_field(
            "data",
            format!("file data exceeds the 512 MB limit ({} bytes)", data.len()),
        ));
    }

    tracing::debug!(size_bytes = data.len(), "uploading file");

    let path = format!("/files?{}", API_VERSION);
    let purpose_str = purpose.as_str().to_string();
    let filename_owned = filename.to_string();

    let response = client
        .post_multipart(&path, move || {
            let file_part =
                reqwest::multipart::Part::bytes(data.to_vec()).file_name(filename_owned.clone());
            reqwest::multipart::Form::new()
                .part("file", file_part)
                .text("purpose", purpose_str.clone())
        })
        .await?;

    let file = response.json::<FileObject>().await?;

    tracing::debug!(file_id = %file.id, "file uploaded");
    Ok(file)
}

/// Get a file by ID.
///
/// # Example
///
/// ```rust,no_run
/// # use azure_ai_foundry_core::client::FoundryClient;
/// # use azure_ai_foundry_agents::file;
/// # async fn example(client: &FoundryClient) -> azure_ai_foundry_core::error::FoundryResult<()> {
/// let file = file::get(client, "file-abc123").await?;
/// println!("File: {} ({} bytes)", file.filename, file.bytes);
/// # Ok(())
/// # }
/// ```
///
/// # Tracing
///
/// Emits a span named `foundry::files::get` with field `file_id`.
#[tracing::instrument(
    name = "foundry::files::get",
    skip(client),
    fields(file_id = %file_id)
)]
pub async fn get(client: &FoundryClient, file_id: &str) -> FoundryResult<FileObject> {
    tracing::debug!("getting file");
    FoundryClient::validate_resource_id(file_id)?;
    let path = format!("/files/{}?{}", file_id, API_VERSION);
    let response = client.get(&path).await?;
    let file = response.json::<FileObject>().await?;

    Ok(file)
}

/// List all files.
///
/// # Example
///
/// ```rust,no_run
/// # use azure_ai_foundry_core::client::FoundryClient;
/// # use azure_ai_foundry_agents::file;
/// # async fn example(client: &FoundryClient) -> azure_ai_foundry_core::error::FoundryResult<()> {
/// let files = file::list(client).await?;
/// for f in files.data {
///     println!("{}: {} ({} bytes)", f.id, f.filename, f.bytes);
/// }
/// # Ok(())
/// # }
/// ```
///
/// # Tracing
///
/// Emits a span named `foundry::files::list`.
#[tracing::instrument(name = "foundry::files::list", skip(client))]
pub async fn list(client: &FoundryClient) -> FoundryResult<FileList> {
    tracing::debug!("listing files");

    let path = format!("/files?{}", API_VERSION);
    let response = client.get(&path).await?;
    let list = response.json::<FileList>().await?;

    tracing::debug!(count = list.data.len(), "files listed");
    Ok(list)
}

/// Delete a file.
///
/// # Example
///
/// ```rust,no_run
/// # use azure_ai_foundry_core::client::FoundryClient;
/// # use azure_ai_foundry_agents::file;
/// # async fn example(client: &FoundryClient) -> azure_ai_foundry_core::error::FoundryResult<()> {
/// let result = file::delete(client, "file-abc123").await?;
/// if result.deleted {
///     println!("File deleted");
/// }
/// # Ok(())
/// # }
/// ```
///
/// # Tracing
///
/// Emits a span named `foundry::files::delete` with field `file_id`.
#[tracing::instrument(
    name = "foundry::files::delete",
    skip(client),
    fields(file_id = %file_id)
)]
pub async fn delete(client: &FoundryClient, file_id: &str) -> FoundryResult<FileDeletionResponse> {
    tracing::debug!("deleting file");
    FoundryClient::validate_resource_id(file_id)?;
    let path = format!("/files/{}?{}", file_id, API_VERSION);
    let response = client.delete(&path).await?;
    let result = response.json::<FileDeletionResponse>().await?;

    tracing::debug!(deleted = result.deleted, "file deletion complete");
    Ok(result)
}

/// Download the content of a file.
///
/// Returns the raw file content as bytes.
///
/// # Example
///
/// ```rust,no_run
/// # use azure_ai_foundry_core::client::FoundryClient;
/// # use azure_ai_foundry_agents::file;
/// # async fn example(client: &FoundryClient) -> azure_ai_foundry_core::error::FoundryResult<()> {
/// let content = file::download(client, "file-abc123").await?;
/// println!("Downloaded {} bytes", content.len());
/// # Ok(())
/// # }
/// ```
///
/// # Tracing
///
/// Emits a span named `foundry::files::download` with field `file_id`.
#[tracing::instrument(
    name = "foundry::files::download",
    skip(client),
    fields(file_id = %file_id)
)]
pub async fn download(client: &FoundryClient, file_id: &str) -> FoundryResult<bytes::Bytes> {
    tracing::debug!("downloading file content");
    FoundryClient::validate_resource_id(file_id)?;
    let path = format!("/files/{}/content?{}", file_id, API_VERSION);
    let data = client.get_bytes(&path).await?;

    tracing::debug!(size_bytes = data.len(), "file content downloaded");
    Ok(data)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::test_utils::{setup_mock_client, TEST_TIMESTAMP};
    use wiremock::matchers::{header, method, path};
    use wiremock::{Mock, MockServer, ResponseTemplate};

    // --- R6: upload() accepts Into<bytes::Bytes> ---

    #[test]
    fn test_upload_accepts_bytes_type() {
        // Verify that Into<bytes::Bytes> is satisfied by both Vec<u8> and Bytes
        fn assert_into_bytes<T: Into<bytes::Bytes>>(_: T) {}
        assert_into_bytes(vec![1u8, 2, 3]);
        assert_into_bytes(bytes::Bytes::from_static(b"hello"));
    }

    // --- Quality: FilePurpose::as_str() ---

    #[test]
    fn test_file_purpose_as_str() {
        assert_eq!(FilePurpose::Assistants.as_str(), "assistants");
        assert_eq!(FilePurpose::AssistantsOutput.as_str(), "assistants_output");
        assert_eq!(FilePurpose::FineTune.as_str(), "fine-tune");
    }

    // --- Cycle 2.1: FileObject deserialization ---

    #[test]
    fn test_file_object_deserialization() {
        let json = serde_json::json!({
            "id": "file-abc",
            "object": "file",
            "bytes": 12345,
            "created_at": TEST_TIMESTAMP,
            "filename": "data.jsonl",
            "purpose": "assistants",
            "status": "processed",
            "status_details": "ready"
        });

        let file: FileObject = serde_json::from_value(json).unwrap();

        assert_eq!(file.id, "file-abc");
        assert_eq!(file.object, "file");
        assert_eq!(file.bytes, 12345);
        assert_eq!(file.created_at, TEST_TIMESTAMP);
        assert_eq!(file.filename, "data.jsonl");
        assert_eq!(file.purpose, FilePurpose::Assistants);
        assert_eq!(file.status, Some("processed".into()));
        assert_eq!(file.status_details, Some("ready".into()));
    }

    // --- Cycle 2.2: FileObject minimal ---

    #[test]
    fn test_file_object_deserialization_minimal() {
        let json = serde_json::json!({
            "id": "file-abc",
            "object": "file",
            "bytes": 100,
            "created_at": TEST_TIMESTAMP,
            "filename": "test.txt",
            "purpose": "assistants"
        });

        let file: FileObject = serde_json::from_value(json).unwrap();

        assert_eq!(file.id, "file-abc");
        assert!(file.status.is_none());
        assert!(file.status_details.is_none());
    }

    // --- Cycle 2.3: FilePurpose serialization ---

    #[test]
    fn test_file_purpose_serialization() {
        assert_eq!(
            serde_json::to_string(&FilePurpose::Assistants).unwrap(),
            "\"assistants\""
        );
        assert_eq!(
            serde_json::to_string(&FilePurpose::AssistantsOutput).unwrap(),
            "\"assistants_output\""
        );
        assert_eq!(
            serde_json::to_string(&FilePurpose::FineTune).unwrap(),
            "\"fine-tune\""
        );
    }

    #[test]
    fn test_file_purpose_deserialization() {
        assert_eq!(
            serde_json::from_str::<FilePurpose>("\"assistants\"").unwrap(),
            FilePurpose::Assistants
        );
        assert_eq!(
            serde_json::from_str::<FilePurpose>("\"assistants_output\"").unwrap(),
            FilePurpose::AssistantsOutput
        );
        assert_eq!(
            serde_json::from_str::<FilePurpose>("\"fine-tune\"").unwrap(),
            FilePurpose::FineTune
        );
    }

    // --- Cycle 2.4: FileList deserialization ---

    #[test]
    fn test_file_list_deserialization() {
        let json = serde_json::json!({
            "object": "list",
            "data": [
                {
                    "id": "file-1",
                    "object": "file",
                    "bytes": 100,
                    "created_at": TEST_TIMESTAMP,
                    "filename": "a.txt",
                    "purpose": "assistants"
                },
                {
                    "id": "file-2",
                    "object": "file",
                    "bytes": 200,
                    "created_at": TEST_TIMESTAMP,
                    "filename": "b.txt",
                    "purpose": "fine-tune"
                }
            ],
            "has_more": false
        });

        let list: FileList = serde_json::from_value(json).unwrap();

        assert_eq!(list.object, "list");
        assert_eq!(list.data.len(), 2);
        assert_eq!(list.data[0].id, "file-1");
        assert_eq!(list.data[1].purpose, FilePurpose::FineTune);
        assert!(!list.has_more);
    }

    // --- Cycle 2.5: FileDeletionResponse deserialization ---

    #[test]
    fn test_file_deletion_response_deserialization() {
        let json = serde_json::json!({
            "id": "file-abc",
            "object": "file.deleted",
            "deleted": true
        });

        let result: FileDeletionResponse = serde_json::from_value(json).unwrap();

        assert_eq!(result.id, "file-abc");
        assert_eq!(result.object, "file.deleted");
        assert!(result.deleted);
    }

    // --- Cycle 2.6: upload() API ---

    #[tokio::test]
    async fn test_upload_file_success() {
        let server = MockServer::start().await;

        let expected_response = serde_json::json!({
            "id": "file-new123",
            "object": "file",
            "bytes": 11,
            "created_at": TEST_TIMESTAMP,
            "filename": "test.txt",
            "purpose": "assistants"
        });

        Mock::given(method("POST"))
            .and(path("/files"))
            .and(header("Authorization", "Bearer test-api-key"))
            .respond_with(ResponseTemplate::new(200).set_body_json(&expected_response))
            .mount(&server)
            .await;

        let client = setup_mock_client(&server).await;

        let file = upload(
            &client,
            "test.txt",
            b"file content".to_vec(),
            FilePurpose::Assistants,
        )
        .await
        .expect("should succeed");

        assert_eq!(file.id, "file-new123");
        assert_eq!(file.filename, "test.txt");
        assert_eq!(file.purpose, FilePurpose::Assistants);
    }

    // --- Cycle 2.7: upload() validation ---

    #[tokio::test]
    async fn test_upload_rejects_empty_filename() {
        let server = MockServer::start().await;
        let client = setup_mock_client(&server).await;

        let result = upload(&client, "  ", b"data".to_vec(), FilePurpose::Assistants).await;

        assert!(result.is_err());
        let err = result.unwrap_err();
        assert!(err.to_string().contains("filename cannot be empty"));
    }

    #[tokio::test]
    async fn test_upload_rejects_empty_data() {
        let server = MockServer::start().await;
        let client = setup_mock_client(&server).await;

        let result = upload(&client, "test.txt", vec![], FilePurpose::Assistants).await;

        assert!(result.is_err());
        let err = result.unwrap_err();
        assert!(err.to_string().contains("file data cannot be empty"));
    }

    // --- Quality: File size validation ---

    #[test]
    fn test_max_file_size_bytes_constant() {
        assert_eq!(MAX_FILE_SIZE_BYTES, 512 * 1024 * 1024);
    }

    #[tokio::test]
    async fn test_upload_rejects_oversized_file() {
        let server = MockServer::start().await;
        let client = setup_mock_client(&server).await;

        // Use a moderately oversized vec (just over the limit) to test the guard
        // without allocating the full 512 MB. We temporarily lower the check by
        // testing the error message contains "512 MB".
        let oversized = vec![0u8; MAX_FILE_SIZE_BYTES + 1];

        let result = upload(&client, "huge.bin", oversized, FilePurpose::Assistants).await;

        assert!(result.is_err());
        let err = result.unwrap_err();
        assert!(
            err.to_string().contains("512 MB"),
            "error should mention the 512 MB limit, got: {}",
            err
        );
    }

    // --- Cycle 2.8: get() API ---

    #[tokio::test]
    async fn test_get_file_success() {
        let server = MockServer::start().await;

        let expected_response = serde_json::json!({
            "id": "file-abc",
            "object": "file",
            "bytes": 500,
            "created_at": TEST_TIMESTAMP,
            "filename": "data.csv",
            "purpose": "assistants"
        });

        Mock::given(method("GET"))
            .and(path("/files/file-abc"))
            .and(header("Authorization", "Bearer test-api-key"))
            .respond_with(ResponseTemplate::new(200).set_body_json(&expected_response))
            .mount(&server)
            .await;

        let client = setup_mock_client(&server).await;

        let file = get(&client, "file-abc").await.expect("should succeed");

        assert_eq!(file.id, "file-abc");
        assert_eq!(file.filename, "data.csv");
    }

    // --- Cycle 2.9: list() API ---

    #[tokio::test]
    async fn test_list_files_success() {
        let server = MockServer::start().await;

        let expected_response = serde_json::json!({
            "object": "list",
            "data": [{
                "id": "file-1",
                "object": "file",
                "bytes": 100,
                "created_at": TEST_TIMESTAMP,
                "filename": "a.txt",
                "purpose": "assistants"
            }],
            "has_more": false
        });

        Mock::given(method("GET"))
            .and(path("/files"))
            .respond_with(ResponseTemplate::new(200).set_body_json(&expected_response))
            .mount(&server)
            .await;

        let client = setup_mock_client(&server).await;

        let list = list(&client).await.expect("should succeed");

        assert_eq!(list.data.len(), 1);
        assert_eq!(list.data[0].id, "file-1");
        assert!(!list.has_more);
    }

    // --- Cycle 2.10: delete() API ---

    #[tokio::test]
    async fn test_delete_file_success() {
        let server = MockServer::start().await;

        let expected_response = serde_json::json!({
            "id": "file-abc",
            "object": "file.deleted",
            "deleted": true
        });

        Mock::given(method("DELETE"))
            .and(path("/files/file-abc"))
            .respond_with(ResponseTemplate::new(200).set_body_json(&expected_response))
            .mount(&server)
            .await;

        let client = setup_mock_client(&server).await;

        let result = delete(&client, "file-abc").await.expect("should succeed");

        assert_eq!(result.id, "file-abc");
        assert!(result.deleted);
    }

    // --- Cycle 2.11: download() API ---

    #[tokio::test]
    async fn test_download_file_success() {
        let server = MockServer::start().await;

        let raw_content = b"hello world file content";

        Mock::given(method("GET"))
            .and(path("/files/file-abc/content"))
            .and(header("Authorization", "Bearer test-api-key"))
            .respond_with(ResponseTemplate::new(200).set_body_bytes(raw_content.to_vec()))
            .mount(&server)
            .await;

        let client = setup_mock_client(&server).await;

        let content = download(&client, "file-abc").await.expect("should succeed");

        assert_eq!(content.as_ref(), raw_content);
    }

    #[tokio::test]
    async fn test_get_file_rejects_path_traversal() {
        let server = MockServer::start().await;
        let client = setup_mock_client(&server).await;
        let result = get(&client, "../evil").await;
        assert!(result.is_err());
        let err = result.unwrap_err();
        assert!(
            matches!(
                err,
                azure_ai_foundry_core::error::FoundryError::Validation { .. }
            ),
            "Expected Validation error, got: {:?}",
            err
        );
    }
}
