//! Common types shared across all Azure AI Foundry crates.

use serde::{Deserialize, Serialize};

/// Usage statistics returned by the API.
///
/// This struct is present in both chat completion and embedding responses,
/// providing token consumption metrics for monitoring and cost tracking.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Usage {
    /// Number of tokens in the prompt (input).
    pub prompt_tokens: u32,

    /// Number of tokens generated by the model (output).
    ///
    /// `None` for embedding requests, which do not generate output tokens.
    pub completion_tokens: Option<u32>,

    /// Total tokens consumed by the request (prompt + completion).
    pub total_tokens: u32,
}
